"""admin rbac and notify pref

Revision ID: 13c65af1ed08
Revises: 846d6d7aad3d
Create Date: 2026-09-19 20:00:07.475562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13c65af1ed08'
down_revision: Union[str, None] = '846d6d7aad3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_fence', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.drop_column('notify_fence')

    op.drop_table('admin_users')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
