"""family tags and group tag binding

Revision ID: 42c715201470
Revises: d31e5913f644
Create Date: 2026-09-19 00:44:12.613955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42c715201470'
down_revision: Union[str, None] = 'd31e5913f644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    with op.batch_alter_table('llm_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_llm_groups_tag', ['tag'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_groups', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_llm_groups_tag', type_='unique')
        batch_op.drop_column('tag')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
