"""active time and minutes cap

Revision ID: a8cff11b7f60
Revises: bd2c96c6e312
Create Date: 2026-09-19 13:33:24.903208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8cff11b7f60'
down_revision: Union[str, None] = 'bd2c96c6e312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_times_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_times_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_minutes_cap', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.drop_column('daily_minutes_cap')

    with op.batch_alter_table('active_times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_times_student_id'))
        batch_op.drop_index(batch_op.f('ix_active_times_day'))

    op.drop_table('active_times')
    # ### end Alembic commands ###
