"""usage_logs add cost

Revision ID: b709aa6c4a71
Revises: 49ff46d65e0f
Create Date: 2026-09-19 00:06:11.264038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b709aa6c4a71'
down_revision: Union[str, None] = '49ff46d65e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
