"""token version

Revision ID: bd2c96c6e312
Revises: ece05fe584f9
Create Date: 2026-09-19 13:27:44.792209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd2c96c6e312'
down_revision: Union[str, None] = 'ece05fe584f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
