"""llm groups

Revision ID: d31e5913f644
Revises: b709aa6c4a71
Create Date: 2026-09-19 00:17:54.376058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd31e5913f644'
down_revision: Union[str, None] = 'b709aa6c4a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('chat_model', sa.String(length=80), nullable=False),
    sa.Column('fence_model', sa.String(length=80), nullable=False),
    sa.Column('api_key', sa.String(length=200), nullable=False),
    sa.Column('daily_message_cap', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_groups')
    # ### end Alembic commands ###
