"""family quiet hours

Revision ID: e859036cdded
Revises: 276a802c72b9
Create Date: 2026-09-19 13:13:45.092077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e859036cdded'
down_revision: Union[str, None] = '276a802c72b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiet_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('quiet_start', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quiet_end', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_settings', schema=None) as batch_op:
        batch_op.drop_column('quiet_end')
        batch_op.drop_column('quiet_start')
        batch_op.drop_column('quiet_enabled')

    # ### end Alembic commands ###
